// tailwind.config.js
const plugin = require("tailwindcss/plugin");

const pxToRem = (px, base = 16) => `${px / base}rem`;

module.exports = {
  theme: {
    screens: {
      sm: pxToRem(640),
      md: pxToRem(768),
      lg: pxToRem(1024),
      xl: pxToRem(1180),

      retina: {
        "min-resolution": "192dpi",
      },
    },
    colors: {
      transparent: "transparent",
      black: "#000000",
      white: "#ffffff",
      primary: {
        "100": "#fef0f2",
        "200": "#fcb6c0",
        "300": "#f9768a",
        "400": "#f73b57",
        "500": "#eb0a2c",
        "600": "#ba0823",
        "700": "#8e061a",
        "800": "#5d0411",
        "900": "#310209",
      },
      secondary: {
        100: "#24569B",
        200: "#16345D",
        300: "#16345D",
        400: "#16345D",
        500: "#16345D",
        600: "#16345D",
        700: "#16345D",
        800: "#16345D",
        900: "#16345D",
      },
      gray: {
        "100": "#f7f7f7",
        "200": "#ededed",
        "300": "#b8b8b8",
        "400": "#999999",
        "500": "#7a7a7a",
        "600": "#616161",
        "700": "#4a4a4a",
        "800": "#303030",
        "900": "#1a1a1a",
      },
      danger: {
        100: "#d43f3a",
        200: "#d43f3a",
        300: "#d43f3a",
      },
      warning: {
        100: "f0ad4e",
        200: "f0ad4e",
        300: "f0ad4e",
      },
      success: {
        100: "#5cb85c",
        200: "#5cb85c",
        300: "#5cb85c",
      },
    },
    spacing: {
      px: "1px",
      "0": "0",
      "1": pxToRem(4),
      "2": pxToRem(8),
      "3": pxToRem(12),
      "4": pxToRem(16),
      "5": pxToRem(20),
      "6": pxToRem(24),
      "8": pxToRem(32),
      "9": pxToRem(36),
      "10": pxToRem(40),
      "12": pxToRem(48),
      "14": pxToRem(56),
      "16": pxToRem(64),
      "20": pxToRem(80),
      "22": pxToRem(88),
      "24": pxToRem(96),
      "30": pxToRem(120),
      "32": pxToRem(128),
      "40": pxToRem(160),
      "48": pxToRem(192),
      "50": pxToRem(200),
      "56": pxToRem(224),
      "64": pxToRem(256),
      "72": pxToRem(288),
      "75": pxToRem(300),
      "80": pxToRem(320),
      "90": pxToRem(370),
      "95": pxToRem(380),
      "100": pxToRem(400),
      "125": pxToRem(500),
      "128": pxToRem(512),
      "150": pxToRem(600),
      "175": pxToRem(700),
    },
    backgroundColor: (theme) => theme("colors"),
    backgroundPosition: {
      bottom: "bottom",
      center: "center",
      left: "left",
      "left-bottom": "left bottom",
      "left-top": "left top",
      right: "right",
      "right-bottom": "right bottom",
      "right-top": "right top",
      top: "top",
    },
    backgroundSize: {
      auto: "auto",
      cover: "cover",
      contain: "contain",
    },
    borderColor: (theme) => ({
      ...theme("colors"),
      default: theme("colors.gray.300", "currentColor"),
    }),
    borderRadius: {
      none: "0",
      4: pxToRem(4),
      8: pxToRem(8),
      full: pxToRem(9999),
    },
    borderWidth: {
      default: "1px",
      "0": "0",
      "1": pxToRem(1),
      "2": pxToRem(2),
      "3": pxToRem(3),
      "4": pxToRem(4),
      "5": pxToRem(5),
    },
    boxShadow: {
      default:
        "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
      md:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      lg:
        "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
      xl:
        "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
      "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
      outline: "0 0 0 3px rgba(66, 153, 225, 0.5)",
      none: "none",
    },
    container: {
      center: true,
      padding: "1em",
    },
    cursor: {
      auto: "auto",
      default: "default",
      pointer: "pointer",
      wait: "wait",
      text: "text",
      move: "move",
      "not-allowed": "not-allowed",
      grab: "grab",
      grabbing: "grabbing",
    },
    fill: {
      current: "currentColor",
    },
    flex: {
      "1": "1 1 0%",
      base: "1 0 0",
      auto: "1 1 auto",
      initial: "0 1 auto",
      none: "none",
    },
    flexGrow: {
      "0": "0",
      default: "1",
    },
    flexShrink: {
      "0": "0",
      default: "1",
    },
    fontFamily: {
      sans: ["Roboto", "sans-serif"],
      serif: ["Roboto", "sans-serif"],
      mono: ["Menlo", "Monaco", "monospace"],
    },
    fontSize: {
      10: pxToRem(10),
      11: pxToRem(11),
      12: pxToRem(12),
      14: pxToRem(14),
      16: pxToRem(16),
      18: pxToRem(18),
      20: pxToRem(20),
      24: pxToRem(24),
      30: pxToRem(30),
      36: pxToRem(36),
      48: pxToRem(48),
      64: pxToRem(64),
    },
    fontWeight: {
      light: "light",
      normal: "normal",
      bold: "bold",
    },
    height: (theme) => ({
      auto: "auto",
      ...theme("spacing"),
      full: "100%",
      screen: "100vh",
    }),
    inset: {
      "0": "0",
      auto: "auto",
      "10": "10%",
      "25": "25%",
      "50": "50%",
      "55": pxToRem(55),
      "60": pxToRem(60),
      "245": pxToRem(245),
      "265": pxToRem(265),
      "-50": "-50%",
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
    lineHeight: {
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2",
    },
    listStyleType: {
      none: "none",
      disc: "disc",
      decimal: "decimal",
    },
    margin: (theme, { negative }) => ({
      auto: "auto",
      ...theme("spacing"),
      ...negative(theme("spacing")),
    }),
    maxHeight: {
      full: "100%",
      screen: "100vh",
    },
    maxWidth: {
      xs: "20rem",
      sm: "24rem",
      md: "28rem",
      lg: pxToRem(960),
      xl: pxToRem(960),
      "960": pxToRem(960),
      full: "100%",
      screen: "100vw",
      auto: "auto",
    },
    minHeight: {
      "0": "0",
      full: "100%",
      screen: "100vh",
    },
    minWidth: {
      "0": "0",
      full: "100%",
      screen: "100vw",
      "90": pxToRem(360),
    },
    objectPosition: {
      bottom: "bottom",
      center: "center",
      left: "left",
      "left-bottom": "left bottom",
      "left-top": "left top",
      right: "right",
      "right-bottom": "right bottom",
      "right-top": "right top",
      top: "top",
    },
    opacity: {
      "0": "0",
      "1": "1",
      "25": "0.25",
      "30": "0.30",
      "50": "0.5",
      "75": "0.75",
      "100": "1",
    },
    order: {
      first: "-9999",
      last: "9999",
      none: "0",
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      "8": "8",
      "9": "9",
      "10": "10",
      "11": "11",
      "12": "12",
    },
    padding: (theme) => theme("spacing"),
    scale: {
      "0": "0",
      "25": ".25",
      "50": ".5",
      "75": ".75",
      "80": ".80",
      "85": ".85",
      "90": ".9",
      "95": ".95",
      "100": "1",
      "105": "1.05",
      "110": "1.1",
      "125": "1.25",
      "150": "1.5",
      "200": "2",
    },
    stroke: {
      current: "currentColor",
    },
    placeholderColor: (theme) => theme("colors"),
    textColor: (theme) => theme("colors"),
    width: (theme) => ({
      auto: "auto",
      ...theme("spacing"),
      "1/2": "calc(50% - 1rem)",
      "1/3": "calc(33.33333% - 1rem)",
      "2/3": "calc(66.66667% - 1rem)",
      "1/4": "calc(25% - 1rem)",
      "2/4": "calc(50% - 1rem)",
      "3/4": "calc(75% - 1rem)",
      "1/5": "calc(20% - 1rem)",
      "2/5": "calc(40% - 1rem)",
      "3/5": "calc(60% - 1rem)",
      "4/5": "calc(80% - 1rem)",
      "1/6": "16.66667%",
      "2/6": "33.33333%",
      "3/6": "50%",
      "4/6": "66.66667%",
      "5/6": "83.33333%",
      "1/12": "8.33333%",
      "2/12": "16.66667%",
      "3/12": "25%",
      "4/12": "33.33333%",
      "5/12": "41.66667%",
      "6/12": "50%",
      "7/12": "58.33333%",
      "8/12": "66.66667%",
      "9/12": "75%",
      "10/12": "83.33333%",
      "11/12": "91.66667%",
      full: "100%",
      screen: "100vw",
    }),
    zIndex: {
      auto: "auto",
      "0": "0",
      "10": "10",
      "20": "20",
      "30": "30",
      "40": "40",
      "50": "50",
      "-10": "-10",
      "-20": "-20",
      "-30": "-30",
      "-40": "-40",
      "-50": "-50",
    },

    gridTemplateRows: {
      layout: "auto",
      1: "repeat(1, minmax(0, 1fr))",
      2: "repeat(2, minmax(0, 1fr))",
      3: "repeat(3, minmax(0, 1fr))",
      4: "repeat(4, minmax(0, 1fr))",
      5: "repeat(5, minmax(0, 1fr))",
      6: "repeat(6, minmax(0, 1fr))",
      7: "repeat(7, minmax(0, 1fr))",
      8: "repeat(8, minmax(0, 1fr))",
      none: "none",
    },
  },
  extend: {},
  variants: {
    accessibility: ["responsive", "hover", "focus", "active", "group-hover"],
    alignContent: ["responsive"],
    alignItems: ["responsive"],
    alignSelf: ["responsive"],
    appearance: ["responsive"],
    backgroundAttachment: ["responsive"],
    backgroundColor: ["responsive", "hover", "focus"],
    backgroundPosition: ["responsive"],
    backgroundRepeat: ["responsive"],
    backgroundSize: ["responsive"],
    borderCollapse: ["responsive"],
    borderColor: ["responsive", "hover", "focus"],
    borderRadius: ["responsive"],
    borderStyle: ["responsive"],
    borderWidth: ["responsive", "hover", "focus"],
    boxShadow: ["responsive", "hover", "focus"],
    cursor: ["responsive", "hover", "focus"],
    display: ["responsive"],
    fill: ["responsive"],
    flex: ["responsive"],
    flexDirection: ["responsive"],
    flexGrow: ["responsive"],
    flexShrink: ["responsive"],
    flexWrap: ["responsive"],
    float: ["responsive"],
    fontFamily: ["responsive"],
    fontSize: ["responsive"],
    fontSmoothing: ["responsive"],
    fontStyle: ["responsive"],
    fontWeight: ["responsive", "hover", "focus"],
    gridTemplateRows: ["responsive"],
    height: ["responsive"],
    inset: ["responsive", "hover", "focus", "group-hover"],
    justifyContent: ["responsive"],
    letterSpacing: ["responsive"],
    lineHeight: ["responsive"],
    listStylePosition: ["responsive"],
    listStyleType: ["responsive"],
    margin: ["responsive", "last"],
    maxHeight: ["responsive"],
    maxWidth: ["responsive"],
    minHeight: ["responsive"],
    minWidth: ["responsive"],
    objectFit: ["responsive"],
    objectPosition: ["responsive"],
    opacity: ["responsive", "hover", "group-hover", "focus"],
    order: ["responsive"],
    outline: ["responsive", "focus"],
    overflow: ["responsive"],
    padding: ["responsive"],
    placeholderColor: ["responsive", "focus"],
    pointerEvents: ["responsive"],
    position: ["responsive", "hover", "group-hover", "focus"],
    resize: ["responsive"],
    scale: ["responsive", "hover", "focus", "active", "focus-within"],
    transformOrigin: ["responsive", "hover", "focus", "focus-within"],
    stroke: ["responsive"],
    space: ["responsive", "hover", "focus"],
    tableLayout: ["responsive"],
    textAlign: ["responsive"],
    textColor: ["responsive", "hover", "focus", "group-hover"],
    textDecoration: ["responsive", "hover", "focus"],
    textTransform: ["responsive"],
    userSelect: ["responsive"],
    verticalAlign: ["responsive"],
    visibility: ["responsive"],
    whitespace: ["responsive"],
    width: ["responsive"],
    wordBreak: ["responsive"],
    zIndex: ["responsive", "hover", "focus"],
  },
  plugins: [
    plugin(function({ addUtilities }) {
      const newUtilities = {
        ".filter-none": {
          filter: "none",
        },
        ".filter-grayscale": {
          filter: "grayscale(100%)",
        },
        ".filter-brightness-0": {
          filter: "brightness(0)",
        },
        ".filter-brightness-25": {
          filter: "brightness(0.25)",
        },
        ".filter-brightness-50": {
          filter: "brightness(0.5)",
        },
        ".filter-brightness-75": {
          filter: "brightness(0.75)",
        },
        ".filter-brightness-100": {
          filter: "brightness(0.1)",
        },
      };

      addUtilities(newUtilities, ["responsive", "hover"]);
    }),
  ],
};
